<?php
require 'backend/config/db.php';
$conn = getDBConnection();

$queries = [
    "CREATE TABLE tamilnadu_cities (
        city_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        city_name VARCHAR2(100) NOT NULL UNIQUE
    )",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Chennai')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Coimbatore')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Madurai')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Tiruchirappalli')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Salem')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Tirunelveli')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Tiruppur')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Vellore')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Erode')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Thoothukudi')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Dindigul')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Thanjavur')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Kanyakumari')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Kanchipuram')",
    "INSERT INTO tamilnadu_cities (city_name) VALUES ('Ooty')"
];

foreach ($queries as $q) {
    echo "Running: $q\n";
    $stmt = oci_parse($conn, $q);
    $r = @oci_execute($stmt);
    if (!$r) {
        $e = oci_error($stmt);
        echo "Error: " . $e['message'] . "\n";
    }
}
echo "Done.\n";
