ALTER TABLE claims ADD CONSTRAINT chk_claims_status_final
CHECK (status IN ('ACTIVE', 'PENDING', 'ACCEPTED', 'VOLUNTEER_ASSIGNED', 'PICKUP_STARTED', 'FOOD_PICKED_UP', 'FOOD_PICKED', 'DELIVERING', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'CLAIMED'));
COMMIT;
EXIT;
