-- Create volunteer_tracking table for real-time delivery tracking
CREATE TABLE volunteer_tracking (
    tracking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_id NUMBER NOT NULL,
    donation_id NUMBER NOT NULL,
    latitude NUMBER(10, 8),
    longitude NUMBER(11, 8),
    status VARCHAR2(50),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tracking_vol FOREIGN KEY (volunteer_id) REFERENCES users(user_id),
    CONSTRAINT fk_tracking_donation FOREIGN KEY (donation_id) REFERENCES food_alerts(alert_id)
);

-- Index for performance
CREATE INDEX idx_tracking_donation ON volunteer_tracking(donation_id);
