-- Add new columns to food_alerts for tracking and priority
ALTER TABLE food_alerts ADD (
    prepared_time TIMESTAMP,
    expiry_time TIMESTAMP,
    priority VARCHAR2(20) DEFAULT 'Normal',
    assigned_time TIMESTAMP,
    pickup_time TIMESTAMP,
    delivery_time TIMESTAMP
);

-- Add rating to users or claims. Let's add average_rating to users and rating to claims.
ALTER TABLE claims ADD rating NUMBER(1) DEFAULT 0;
ALTER TABLE users ADD average_rating NUMBER(3,2) DEFAULT 0;

-- Create Inventory table for NGOs
CREATE TABLE ngo_inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngo_id NUMBER REFERENCES users(user_id),
    food_type VARCHAR2(100) NOT NULL,
    quantity VARCHAR2(100) NOT NULL,
    expiry_time TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'AVAILABLE',
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

exit;
