-- setup_tracking.sql
BEGIN
  -- 1. Create volunteer_tracking table
  BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE volunteer_tracking (
        tracking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        volunteer_id NUMBER NOT NULL,
        donation_id NUMBER NOT NULL,
        latitude NUMBER(10, 8),
        longitude NUMBER(11, 8),
        status VARCHAR2(50),
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_tracking_vol FOREIGN KEY (volunteer_id) REFERENCES users(user_id),
        CONSTRAINT fk_tracking_donation FOREIGN KEY (donation_id) REFERENCES food_alerts(alert_id)
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_tracking_donation ON volunteer_tracking(donation_id)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN NULL; -- Table already exists
      ELSE RAISE;
      END IF;
  END;

  -- 2. Update status constraints in food_alerts
  FOR r IN (
    SELECT ucc.constraint_name 
    FROM user_cons_columns ucc
    JOIN user_constraints uc ON ucc.constraint_name = uc.constraint_name
    WHERE ucc.table_name = 'FOOD_ALERTS' 
    AND (ucc.column_name = 'STATUS' OR ucc.column_name = 'DELIVERY_STATUS')
    AND uc.constraint_type = 'C'
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE FOOD_ALERTS DROP CONSTRAINT ' || r.constraint_name;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;

  EXECUTE IMMEDIATE 'ALTER TABLE food_alerts ADD CONSTRAINT chk_fa_status 
    CHECK (status IN (''AVAILABLE'', ''PENDING'', ''NGO_ASSIGNED'', ''VOLUNTEER_ASSIGNED'', ''ACCEPTED'', ''PICKED_UP'', ''ON_DELIVERY'', ''DELIVERED'', ''COMPLETED'', ''EXPIRED'', ''CLAIMED''))';

  EXECUTE IMMEDIATE 'ALTER TABLE food_alerts ADD CONSTRAINT chk_fa_del_status 
    CHECK (delivery_status IN (''PENDING'', ''ACCEPTED'', ''PICKED_UP'', ''ON_DELIVERY'', ''DELIVERED'', ''COMPLETED''))';

  -- 3. Update status constraints in claims
  FOR r IN (
    SELECT ucc.constraint_name 
    FROM user_cons_columns ucc
    JOIN user_constraints uc ON ucc.constraint_name = uc.constraint_name
    WHERE ucc.table_name = 'CLAIMS' 
    AND ucc.column_name = 'STATUS'
    AND uc.constraint_type = 'C'
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS DROP CONSTRAINT ' || r.constraint_name;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;

  EXECUTE IMMEDIATE 'ALTER TABLE claims ADD CONSTRAINT chk_claims_status 
    CHECK (status IN (''ACTIVE'', ''ASSIGNED'', ''ACCEPTED'', ''PICKED_UP'', ''ON_DELIVERY'', ''DELIVERED'', ''COMPLETED'', ''CANCELLED''))';
END;
/
COMMIT;
EXIT;
